[package]
name = "nft_airdrop"
version = "0.1.0"
description = "NFT airdrop program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "nft_airdrop"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]


[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"]}
anchor-spl = { version = "0.31.1", features = ["metadata"] }
mpl-token-metadata = "5.1.0"
solana-program = "2.2.1"