[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
airdrop = "11111111111111111111111111111111"
nft_airdrop = "11111111111111111111111111111111"
spl_token_staking = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keys/{PUBLIC_KEY}.json"

[workspace]
members = ["programs/airdrop", "programs/nft_airdrop", "programs/spl_token_staking"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
